import Link from "next/link";
import LiveGameCard from "@/components/LiveGameCard";
import StandingsTable from "@/components/StandingsTable";
import AutoRefresh from "@/components/AutoRefresh";
import PlayerAvatar from "@/components/PlayerAvatar";
import { prisma } from "@/lib/prisma";
import { computeStandings, selectQualifiers } from "@/lib/tournament/standings";
import { calculateMvpRankings } from "@/lib/tournament/mvp";

export const dynamic = "force-dynamic";
export default async function Home() {
  const tournament = await prisma.tournament.findFirst({ include: { groups: { include: { teams: { include: { group: true } } }, orderBy: { name: "asc" } }, matchups: { orderBy: { order: "asc" } } }, orderBy: { createdAt: "desc" } });
  if (!tournament) return <main className="mx-auto max-w-7xl p-6">Run the seed script first.</main>;
  const [live, upcoming, voteGroups, mvpGames] = await Promise.all([
    prisma.game.findMany({ where: { status: { in: ["LIVE", "INTERRUPTED"] }, matchup: { tournamentId: tournament.id } }, include: { matchup: true, homeTeam: true, awayTeam: true, homePair: { include: { playerA: true, playerB: true } }, awayPair: { include: { playerA: true, playerB: true } } }, orderBy: { startedAt: "asc" } }),
    prisma.matchup.findMany({ where: { tournamentId: tournament.id, status: { in: ["READY", "LINEUP_PENDING", "SCHEDULED"] } }, include: { homeTeam: true, awayTeam: true }, orderBy: [{ scheduledAt: "asc" }, { order: "asc" }], take: 6 }),
    prisma.fanVote.groupBy({ by: ["playerId"], where: { tournamentId: tournament.id }, _count: { _all: true }, orderBy: { _count: { playerId: "desc" } }, take: 5 }),
    prisma.game.findMany({
      where: { matchup: { tournamentId: tournament.id }, status: { in: ["COMPLETED", "FORFEITED"] } },
      include: {
        homePair: { include: { playerA: { include: { team: true } }, playerB: { include: { team: true } } } },
        awayPair: { include: { playerA: { include: { team: true } }, playerB: { include: { team: true } } } },
      },
    }),
  ]);
  const fanPlayers = await prisma.player.findMany({ where: { id: { in: voteGroups.map((row) => row.playerId) } }, include: { team: true } });
  const fanById = new Map(fanPlayers.map((player) => [player.id, player]));
  const tables = tournament.groups.map((group) => computeStandings(group.teams, tournament.matchups.filter((matchup) => matchup.groupLabel === group.name)));
  const qualifiers = selectQualifiers(tables);
  const mvp = calculateMvpRankings(mvpGames);
  return <main><AutoRefresh interval={5000}/><section className="relative overflow-hidden border-b border-line bg-ink text-white"><div className="hero-banner-image absolute inset-0 bg-[url('/pickleball.png')] bg-cover bg-center opacity-90"/><div className="absolute inset-0 bg-gradient-to-r from-ink/82 via-ink/45 to-ink/18"/><div className="absolute inset-0 bg-ink/10"/><div className="relative mx-auto max-w-7xl px-4 py-12"><div className="label text-lime">Official live tournament hub</div><h1 className="mt-2 max-w-5xl text-4xl font-black uppercase leading-none md:text-6xl">{tournament.name}</h1><p className="mt-4 max-w-3xl text-white/75">3 groups · 12 teams · 84 pairs · 168 players. Live courts, standings, wildcard race, bracket progression, Fan Favorite votes, and transparent MVP numbers.</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/bracket" className="btn border-lime bg-lime text-ink">View bracket</Link><Link href="/fan-favorite" className="btn border-white/40 text-white">Vote Fan Favorite</Link><Link href="/mvp" className="btn border-white/40 text-white">MVP rankings</Link></div></div></section><div className="mx-auto max-w-7xl space-y-10 px-4 py-8">
  <section><div className="mb-4 flex items-end justify-between"><div><div className="label">Now playing</div><h2 className="text-2xl font-black uppercase">Live courts</h2></div><span className="bg-flame/10 px-3 py-1 text-xs font-bold text-flame">{live.length} live</span></div>{live.length ? <div className="grid gap-4 lg:grid-cols-2">{live.map((game) => <LiveGameCard key={game.id} initial={game}/>)}</div> : <div className="panel p-8 text-center text-gray-500">No game is live right now. Upcoming team matchups are below.</div>}</section>
  <section><div className="mb-4 flex flex-wrap items-end justify-between gap-2"><div><div className="label">Road to the semifinals</div><h2 className="text-2xl font-black uppercase">Group standings</h2></div>{qualifiers.wildcard && <div className="border border-amber-300 bg-amber-50 px-3 py-2 text-sm"><span className="label">Current wildcard</span><strong className="ml-2">{qualifiers.wildcard.team.name}</strong></div>}</div><div className="grid gap-5 lg:grid-cols-3">{tournament.groups.map((group, index) => <div className="panel" key={group.id}><div className="flex items-center justify-between border-b border-line p-4"><h3 className="font-black uppercase">{group.name}</h3><Link href={`/groups/${group.slug}`} className="text-xs font-bold text-court">Full group →</Link></div><StandingsTable rows={tables[index]!}/></div>)}</div></section>
  <section className="grid gap-6 lg:grid-cols-2"><div><div className="mb-4"><div className="label">Next on court</div><h2 className="text-2xl font-black uppercase">Upcoming team matchups</h2></div><div className="space-y-3">{upcoming.map((matchup) => <Link key={matchup.id} href={`/matches/${matchup.id}`} className="panel flex items-center justify-between gap-3 p-4 hover:border-court"><div><div className="label">{matchup.groupLabel || matchup.stage} · {matchup.roundLabel} · Court {matchup.courtLabel || "TBA"}</div><div className="font-black">{matchup.homeTeam?.name || "TBD"} vs {matchup.awayTeam?.name || "TBD"}</div></div><span className="text-xs font-bold">{matchup.status.replaceAll("_", " ")}</span></Link>)}</div></div><div><div className="mb-4"><div className="label">Crowd pulse</div><h2 className="text-2xl font-black uppercase">Fan Favorite leaders</h2></div><div className="panel divide-y divide-line">{voteGroups.length ? voteGroups.map((row, index) => { const player = fanById.get(row.playerId); return player ? <div key={row.playerId} className="flex items-center gap-3 p-4"><span className="w-6 text-xl font-black">{index + 1}</span><PlayerAvatar {...player} size="sm"/><div className="flex-1"><div className="font-black">{player.displayName || `${player.firstName} ${player.lastName}`}</div><div className="text-xs text-gray-500">{player.team.shortName}</div></div><strong>{row._count._all} votes</strong></div> : null; }) : <div className="p-8 text-center text-gray-500">No votes yet.</div>}<Link href="/fan-favorite" className="block p-4 text-center text-sm font-bold text-court">View live rankings →</Link></div></div></section>
  <section><div className="mb-4"><div className="label">Numbers supporting the judges</div><h2 className="text-2xl font-black uppercase">Current MVP leaders</h2></div><div className="grid gap-4 md:grid-cols-2"><MvpLeader title="Male MVP" row={mvp.male[0]}/><MvpLeader title="Female MVP" row={mvp.female[0]}/></div></section>
  </div></main>;
}
function MvpLeader({ title, row }: { title: string; row?: ReturnType<typeof calculateMvpRankings>["male"][number] }) { return <Link href="/mvp" className="panel flex items-center gap-4 p-5 hover:border-court"><div className="flex-1"><div className="label">{title}</div>{row ? <><div className="mt-1 text-xl font-black">{row.player.displayName || `${row.player.firstName} ${row.player.lastName}`}</div><div className="text-sm text-gray-500">{row.player.team.shortName} · {row.wins}-{row.losses} · {row.confidence}% confidence</div></> : <div className="mt-2 text-gray-500">Complete games to populate.</div>}</div>{row && <div className="text-right"><div className="text-3xl font-black text-court">{row.mvpIndex}</div><div className="label">MVP index</div></div>}</Link>; }
