import { prisma } from "@/lib/prisma";
import AutoRefresh from "@/components/AutoRefresh";

export const dynamic = "force-dynamic";
export default async function Bracket({ searchParams }: { searchParams: Promise<{ success?: string }> }) {
  const query = await searchParams;
  const tournament = await prisma.tournament.findFirst({ orderBy: { createdAt: "desc" } });
  const matchups = tournament ? await prisma.matchup.findMany({ where: { tournamentId: tournament.id, stage: { in: ["SEMIFINAL", "FINAL"] } }, include: { homeTeam: true, awayTeam: true, winnerTeam: true }, orderBy: { order: "asc" } }) : [];
  const semifinals = matchups.filter((matchup) => matchup.stage === "SEMIFINAL");
  const final = matchups.find((matchup) => matchup.stage === "FINAL");
  return <main className="mx-auto max-w-7xl px-4 py-8"><AutoRefresh interval={5000}/>{query.success && <div className="mb-5 border border-emerald-300 bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{query.success}</div>}<div className="label">Knockout stage</div><h1 className="text-4xl font-black uppercase">Championship Bracket</h1><p className="mt-2 text-gray-500">Three group winners plus the best second-place team advance. Assignments are recalculated when group results are corrected or undone.</p><div className="mt-10 grid items-center gap-10 lg:grid-cols-[1fr_120px_1fr]"><div className="space-y-8"><BracketCard title="Semifinal 1" matchup={semifinals[0]}/><BracketCard title="Semifinal 2" matchup={semifinals[1]}/></div><div className="hidden h-px bg-line lg:block"/><BracketCard title="Grand Final" matchup={final}/></div>{!matchups.length && <div className="panel mt-8 p-10 text-center text-gray-500">The knockout bracket appears after recalculation. Teams remain TBD until the group stage is complete.</div>}</main>;
}
function BracketCard({ title, matchup }: { title: string; matchup?: any }) { return <div className="panel overflow-hidden"><div className="flex justify-between bg-ink px-4 py-2 text-xs font-black uppercase tracking-widest text-white"><span>{title}</span><span>{matchup?.status?.replaceAll("_", " ") || "WAITING"}</span></div><div className="divide-y divide-line"><div className={`flex justify-between p-4 font-black ${matchup?.winnerTeamId && matchup.winnerTeamId === matchup.homeTeamId ? "bg-emerald-50 text-court" : ""}`}><span>{matchup?.homeTeam?.name || "TBD"}</span><span>{matchup?.homeWins ?? 0}</span></div><div className={`flex justify-between p-4 font-black ${matchup?.winnerTeamId && matchup.winnerTeamId === matchup.awayTeamId ? "bg-emerald-50 text-court" : ""}`}><span>{matchup?.awayTeam?.name || "TBD"}</span><span>{matchup?.awayWins ?? 0}</span></div></div>{matchup?.courtLabel && <div className="border-t border-line p-2 text-center text-xs text-gray-500">Court {matchup.courtLabel}</div>}</div>; }
