import type { ReactNode } from "react";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { getCurrentUser } from "@/lib/auth";
import AdminNav from "@/components/AdminNav";
import FlashMessage from "@/components/FlashMessage";
import SubmitButton from "@/components/SubmitButton";
import { formatPlayerDisplayName } from "@/lib/player-name";

export const dynamic = "force-dynamic";
export default async function SimulationPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const user = await getCurrentUser(); if (!user || user.role !== "ADMIN") redirect("/login");
  const query = await searchParams;
  const tournament = await prisma.tournament.findFirst({ orderBy: { createdAt: "desc" }, select: { id: true, simulationMode: true } });
  if (!tournament) return <main className="admin-shell">No tournament.</main>;
  const [divisions, matchups, games, players, runs] = await Promise.all([
    prisma.division.findMany({ where: { tournamentId: tournament.id }, select: { id: true, name: true }, orderBy: [{ sortOrder: "asc" }, { name: "asc" }] }),
    prisma.matchup.findMany({ where: { tournamentId: tournament.id, status: { notIn: ["COMPLETED", "FORFEITED"] } }, select: { id: true, groupLabel: true, stage: true, homeTeam: { select: { shortName: true } }, awayTeam: { select: { shortName: true } } }, orderBy: { order: "asc" } }),
    prisma.game.findMany({ where: { matchup: { tournamentId: tournament.id, status: { notIn: ["COMPLETED", "FORFEITED"] } } }, select: { id: true, gameNumber: true, matchup: { select: { roundLabel: true } }, homeTeam: { select: { shortName: true } }, awayTeam: { select: { shortName: true } } }, orderBy: [{ matchup: { order: "asc" } }, { gameNumber: "asc" }] }),
    prisma.player.findMany({ where: { tournamentId: tournament.id, participationStatus: "CONFIRMED", teamId: { not: null } }, select: { id: true, firstName: true, middleInitial: true, lastName: true, displayName: true, team: { select: { shortName: true } } }, orderBy: [{ team: { shortName: "asc" } }, { firstName: "asc" }] }),
    prisma.simulationRun.findMany({ where: { tournamentId: tournament.id }, select: { id: true, kind: true, seed: true, status: true, createdAt: true, error: true }, orderBy: { createdAt: "desc" }, take: 20 }),
  ]);
  return <main className="admin-shell"><AdminNav/><FlashMessage {...query}/><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="label">Admin-only test controls</div><h1 className="text-3xl font-black uppercase md:text-4xl">Simulation Center</h1></div><span className={`px-4 py-2 text-xs font-black uppercase ${tournament.simulationMode ? "bg-amber-300 text-ink" : "bg-gray-200 text-gray-600"}`}>{tournament.simulationMode ? "Simulation mode enabled" : "Simulation mode disabled"}</span></div><div className="mt-5 border-2 border-amber-400 bg-amber-50 p-4 font-black text-amber-950">SIMULATION MODE — TEST DATA MAY BE MODIFIED OR RESET</div>
  {!tournament.simulationMode ? <form action="/api/admin/settings" method="post" className="mt-5"><input type="hidden" name="action" value="enable-simulation"/><SubmitButton className="btn-primary" pendingLabel="Enabling…">Enable Simulation Mode</SubmitButton></form> : <div className="mt-6 grid gap-5 lg:grid-cols-2">
    <Tool title="Quick scenarios" description="Load legacy Open-sample stress scenarios plus voting/recovery cases. Use Division / stage for generic formats."><form action="/api/admin/simulation" method="post" className="space-y-3"><input type="hidden" name="kind" value="QUICK_SCENARIO"/><Seed/><select name="targetId" className="w-full border border-line p-3"><option value="FRESH_TOURNAMENT">Fresh tournament</option><option value="LINEUPS_PENDING">Lineups pending</option><option value="MID_GROUP_STAGE">Mid-group stage</option><option value="GROUP_ALMOST_COMPLETE">Group stage almost complete</option><option value="THREE_WAY_STANDINGS_TIE">Three-way standings tie</option><option value="WILDCARD_TIEBREAK">Wildcard tiebreak scenario</option><option value="SEMIFINALS_READY">Semifinals ready</option><option value="FINAL_READY">Final ready</option><option value="TOURNAMENT_COMPLETED">Tournament completed</option><option value="PLAYER_NO_SHOW">Player no-show forfeit</option><option value="TEAM_FORFEIT">Team matchup forfeit</option><option value="INTERRUPTED_LIVE_GAME">Interrupted live match</option><option value="SCORE_CORRECTION">Score correction</option><option value="FAN_CLOSE_RACE">Fan Favorite close race</option><option value="FAN_TIED_RANKINGS">Fan Favorite tied rankings</option><option value="INVALID_VOTING_ATTEMPTS">Invalid voting-code attempts</option><option value="REUSED_VOTING_CODES">Reused voting codes</option><option value="REVOKED_VOTING_CODES">Revoked voting codes</option></select><ScoreOptions/><AutoPairs/><SubmitButton className="btn-primary w-full" pendingLabel="Running…">Run quick scenario</SubmitButton></form></Tool>
    <Tool title="Single match" description="Apply a deterministic result to one real match record."><form action="/api/admin/simulation" method="post" className="space-y-3"><input type="hidden" name="kind" value="GAME"/><Seed/><select name="targetId" required className="w-full border border-line p-3"><option value="">Select match</option>{games.map((game) => <option key={game.id} value={game.id}>{game.matchup.roundLabel} · {game.homeTeam.shortName}-{game.awayTeam.shortName} · M{game.gameNumber}</option>)}</select><div className="grid grid-cols-2 gap-3"><select name="winner" className="border border-line p-3"><option value="RANDOM">Random winner</option><option value="HOME">Home wins</option><option value="AWAY">Away wins</option></select><ScoreStyle/></div><SubmitButton className="btn-primary w-full" pendingLabel="Running…">Simulate match</SubmitButton></form></Tool>
    <Tool title="Team matchup" description="Simulate the selected matchup under its stage rules. Playoffs stop as soon as the series is clinched."><form action="/api/admin/simulation" method="post" className="space-y-3"><input type="hidden" name="kind" value="MATCHUP"/><Seed/><select name="targetId" required className="w-full border border-line p-3"><option value="">Select team matchup</option>{matchups.filter((matchup) => matchup.homeTeam && matchup.awayTeam).map((matchup) => <option key={matchup.id} value={matchup.id}>{matchup.groupLabel || matchup.stage} · {matchup.homeTeam?.shortName} vs {matchup.awayTeam?.shortName}</option>)}</select><select name="matchupOutcome" className="w-full border border-line p-3"><option value="RANDOM">Random result</option><option value="HOME">Force home win</option><option value="AWAY">Force away win</option><option value="SWEEP_HOME">Home sweep</option><option value="SWEEP_AWAY">Away sweep</option><option value="CLOSE_HOME">Closest home win</option><option value="CLOSE_AWAY">Closest away win</option></select><ScoreStyle/><AutoPairs/><SubmitButton className="btn-primary w-full" pendingLabel="Running…">Simulate team matchup</SubmitButton></form></Tool>
    <Tool title="Division / stage" description="Simulate any configured stage without assuming the original Open format. Automatic progression is recalculated between stages."><form action="/api/admin/simulation" method="post" className="space-y-3"><input type="hidden" name="kind" value="STAGE"/><Seed/><select name="divisionId" className="w-full border border-line p-3"><option value="">All divisions</option>{divisions.map((division) => <option key={division.id} value={division.id}>{division.name}</option>)}</select><select name="stage" className="w-full border border-line p-3"><option value="GROUP">Group</option><option value="ROUND_ROBIN">Round robin</option><option value="QUARTERFINAL">Quarterfinal</option><option value="SEMIFINAL">Semifinal</option><option value="FINAL">Final</option><option value="THIRD_PLACE">Third place</option><option value="CUSTOM">Custom</option></select><ScoreOptions/><AutoPairs/><SubmitButton className="btn-primary w-full" pendingLabel="Running…">Simulate selected stage</SubmitButton></form><form action="/api/admin/simulation" method="post" className="mt-3 space-y-3 border-t border-line pt-3"><input type="hidden" name="kind" value="ENTIRE_TOURNAMENT"/><Seed/><select name="divisionId" className="w-full border border-line p-3"><option value="">All divisions</option>{divisions.map((division) => <option key={division.id} value={division.id}>{division.name}</option>)}</select><ScoreOptions/><AutoPairs/><SubmitButton className="btn-ghost w-full" pendingLabel="Running…">Simulate all configured stages</SubmitButton></form></Tool>
    <Tool title="Fan Favorite simulation" description="Create valid used codes and votes in the same production tables."><form action="/api/admin/simulation" method="post" className="space-y-3"><input type="hidden" name="kind" value="FAN_VOTING"/><Seed/><input type="number" name="count" min="1" max="500" defaultValue="30" className="w-full border border-line p-3"/><select name="selectedPlayerId" className="w-full border border-line p-3"><option value="">Random distribution</option>{players.map((player) => <option key={player.id} value={player.id}>{player.team?.shortName || "Unassigned"} · {formatPlayerDisplayName(player)}</option>)}</select><SubmitButton className="btn-primary w-full" pendingLabel="Running…">Simulate voting burst</SubmitButton></form></Tool>
    <Tool title="Undo latest simulation" description="Restore the automatic checkpoint created before the selected run."><form action="/api/admin/undo" method="post" className="space-y-3"><input type="hidden" name="action" value="simulation"/><select name="runId" className="w-full border border-line p-3"><option value="">Latest completed run</option>{runs.filter((run) => run.status === "COMPLETED").map((run) => <option key={run.id} value={run.id}>{run.kind} · {run.seed} · {run.createdAt.toLocaleString()}</option>)}</select><SubmitButton className="btn border-red-600 bg-red-600 text-white w-full" pendingLabel="Undoing…">Undo simulation</SubmitButton></form></Tool>
  </div>}
  <section className="panel mt-6 overflow-hidden"><div className="border-b border-line p-4"><h2 className="text-xl font-black uppercase">Recent simulation runs</h2></div><div className="divide-y divide-line md:hidden">{runs.length ? runs.map((run) => <article key={run.id} className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="font-black">{run.kind}</div><div className="truncate text-[10px] text-gray-400">{run.id}</div></div><span className="shrink-0 border border-line bg-paper px-2 py-1 text-[10px] font-black uppercase">{run.status}</span></div><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs text-gray-500"><span>Seed <strong className="font-mono text-ink">{run.seed || "—"}</strong></span><span>{run.createdAt.toLocaleString()}</span></div>{run.error && <div className="mt-2 text-xs font-bold text-red-700">{run.error}</div>}</article>) : <div className="p-6 text-center text-sm text-gray-500">No simulation runs yet.</div>}</div><div className="hidden overflow-x-auto md:block"><table className="w-full text-sm"><thead className="bg-ink text-left text-white"><tr><th className="p-3">Run</th><th className="p-3">Seed</th><th className="p-3">Status</th><th className="p-3">Created</th><th className="p-3">Error</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id} className="border-b border-line"><td className="p-3 font-bold">{run.kind}<div className="text-xs font-normal text-gray-500">{run.id}</div></td><td className="p-3 font-mono">{run.seed || "—"}</td><td className="p-3">{run.status}</td><td className="p-3">{run.createdAt.toLocaleString()}</td><td className="max-w-sm p-3 text-red-700">{run.error || "—"}</td></tr>)}</tbody></table></div></section></main>;
}
function Tool({ title, description, children }: { title: string; description: string; children: ReactNode }) { return <section className="panel p-5"><h2 className="text-xl font-black uppercase">{title}</h2><p className="mb-4 mt-1 hidden text-sm text-gray-500 md:block">{description}</p>{children}</section>; }
function Seed() { return <label className="block"><span className="label">Simulation seed</span><input name="seed" defaultValue="20260729" className="mt-1 w-full border border-line p-3 font-mono"/></label>; }
function AutoPairs() { return <label className="flex items-start gap-3 border border-line bg-paper p-3 text-sm font-bold"><input type="checkbox" name="autoGeneratePairs" defaultChecked className="mt-1"/> <span>Generate missing valid pairs from confirmed team members</span></label>; }
function ScoreStyle() { return <select name="scoreStyle" className="w-full border border-line p-3"><option value="RANDOM">Random score</option><option value="DOMINANT">Dominant</option><option value="CLOSE">Close</option><option value="DEUCE">Deuce / extended</option></select>; }
function ScoreOptions() { return <div className="grid grid-cols-2 gap-3"><select name="matchupOutcome" className="border border-line p-3"><option value="RANDOM">Random outcomes</option><option value="HOME">Home-favored</option><option value="AWAY">Away-favored</option><option value="CLOSE_HOME">Closest home win</option><option value="CLOSE_AWAY">Closest away win</option></select><ScoreStyle/></div>; }
