import type { ReactNode } from "react";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { getCurrentUser } from "@/lib/auth";
import AdminNav from "@/components/AdminNav";
import FlashMessage from "@/components/FlashMessage";

export const dynamic = "force-dynamic";
export default async function SimulationPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  const user = await getCurrentUser(); if (!user || user.role !== "ADMIN") redirect("/login");
  const query = await searchParams;
  const tournament = await prisma.tournament.findFirst({ orderBy: { createdAt: "desc" } });
  if (!tournament) return <main className="p-8">No tournament.</main>;
  const [matchups, games, players, runs] = await Promise.all([
    prisma.matchup.findMany({ where: { tournamentId: tournament.id }, include: { homeTeam: true, awayTeam: true }, orderBy: { order: "asc" } }),
    prisma.game.findMany({ where: { matchup: { tournamentId: tournament.id } }, include: { matchup: true, homeTeam: true, awayTeam: true }, orderBy: [{ matchup: { order: "asc" } }, { gameNumber: "asc" }] }),
    prisma.player.findMany({ where: { team: { group: { tournamentId: tournament.id } } }, include: { team: true }, orderBy: [{ team: { shortName: "asc" } }, { firstName: "asc" }] }),
    prisma.simulationRun.findMany({ where: { tournamentId: tournament.id }, include: { createdBy: true }, orderBy: { createdAt: "desc" }, take: 20 }),
  ]);
  return <main className="mx-auto max-w-7xl px-4 py-8"><AdminNav/><FlashMessage {...query}/><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="label">Admin-only test controls</div><h1 className="text-4xl font-black uppercase">Simulation Center</h1></div><span className={`px-4 py-2 text-xs font-black uppercase ${tournament.simulationMode ? "bg-amber-300 text-ink" : "bg-gray-200 text-gray-600"}`}>{tournament.simulationMode ? "Simulation mode enabled" : "Simulation mode disabled"}</span></div><div className="mt-5 border-2 border-amber-400 bg-amber-50 p-4 font-black text-amber-950">SIMULATION MODE — TEST DATA MAY BE MODIFIED OR RESET</div>
  {!tournament.simulationMode ? <form action="/api/admin/settings" method="post" className="mt-5"><input type="hidden" name="action" value="enable-simulation"/><button className="btn-primary">Enable Simulation Mode</button></form> : <div className="mt-6 grid gap-5 lg:grid-cols-2">
    <Tool title="Quick scenarios" description="Load common recovery, bracket, voting, and completion states."><form action="/api/admin/simulation" method="post" className="space-y-3"><input type="hidden" name="kind" value="QUICK_SCENARIO"/><Seed/><select name="targetId" className="w-full border border-line p-3"><option value="FRESH_TOURNAMENT">Fresh tournament</option><option value="LINEUPS_PENDING">Lineups pending</option><option value="MID_GROUP_STAGE">Mid-group stage</option><option value="GROUP_ALMOST_COMPLETE">Group stage almost complete</option><option value="THREE_WAY_STANDINGS_TIE">Three-way standings tie</option><option value="WILDCARD_TIEBREAK">Wildcard tiebreak scenario</option><option value="SEMIFINALS_READY">Semifinals ready</option><option value="FINAL_READY">Final ready</option><option value="TOURNAMENT_COMPLETED">Tournament completed</option><option value="PLAYER_NO_SHOW">Player no-show forfeit</option><option value="TEAM_FORFEIT">Team matchup forfeit</option><option value="INTERRUPTED_LIVE_GAME">Interrupted live game</option><option value="SCORE_CORRECTION">Score correction</option><option value="FAN_CLOSE_RACE">Fan Favorite close race</option><option value="FAN_TIED_RANKINGS">Fan Favorite tied rankings</option><option value="INVALID_VOTING_ATTEMPTS">Invalid voting-code attempts</option><option value="REUSED_VOTING_CODES">Reused voting codes</option><option value="REVOKED_VOTING_CODES">Revoked voting codes</option></select><ScoreOptions/><button className="btn-primary w-full">Run quick scenario</button></form></Tool>
    <Tool title="Single game" description="Apply a deterministic result to one real game record."><form action="/api/admin/simulation" method="post" className="space-y-3"><input type="hidden" name="kind" value="GAME"/><Seed/><select name="targetId" required className="w-full border border-line p-3"><option value="">Select game</option>{games.map((game) => <option key={game.id} value={game.id}>{game.matchup.roundLabel} · {game.homeTeam.shortName}-{game.awayTeam.shortName} · G{game.gameNumber}</option>)}</select><div className="grid grid-cols-2 gap-3"><select name="winner" className="border border-line p-3"><option value="RANDOM">Random winner</option><option value="HOME">Home wins</option><option value="AWAY">Away wins</option></select><ScoreStyle/></div><button className="btn-primary w-full">Simulate game</button></form></Tool>
    <Tool title="Team matchup" description="Simulate all seven games with sweep, close, forced, or random outcomes."><form action="/api/admin/simulation" method="post" className="space-y-3"><input type="hidden" name="kind" value="MATCHUP"/><Seed/><select name="targetId" required className="w-full border border-line p-3"><option value="">Select team matchup</option>{matchups.filter((matchup) => matchup.homeTeam && matchup.awayTeam).map((matchup) => <option key={matchup.id} value={matchup.id}>{matchup.groupLabel || matchup.stage} · {matchup.homeTeam?.shortName} vs {matchup.awayTeam?.shortName}</option>)}</select><select name="matchupOutcome" className="w-full border border-line p-3"><option value="RANDOM">Random result</option><option value="HOME">Force home win</option><option value="AWAY">Force away win</option><option value="SWEEP_HOME">Home sweep 7-0</option><option value="SWEEP_AWAY">Away sweep 0-7</option><option value="CLOSE_HOME">Home wins 4-3</option><option value="CLOSE_AWAY">Away wins 4-3</option></select><ScoreStyle/><button className="btn-primary w-full">Simulate team matchup</button></form></Tool>
    <Tool title="Round / stage" description="Simulate the remaining real records for a selected stage or the entire tournament."><form action="/api/admin/simulation" method="post" className="space-y-3"><Seed/><select name="kind" className="w-full border border-line p-3"><option value="GROUP_STAGE">Remaining group stage</option><option value="SEMIFINAL">Semifinals</option><option value="FINAL">Final</option><option value="ENTIRE_TOURNAMENT">Entire tournament</option></select><ScoreOptions/><button className="btn-primary w-full">Simulate stage</button></form></Tool>
    <Tool title="Fan Favorite simulation" description="Create valid used codes and votes in the same production tables."><form action="/api/admin/simulation" method="post" className="space-y-3"><input type="hidden" name="kind" value="FAN_VOTING"/><Seed/><input type="number" name="count" min="1" max="500" defaultValue="30" className="w-full border border-line p-3"/><select name="selectedPlayerId" className="w-full border border-line p-3"><option value="">Random distribution</option>{players.map((player) => <option key={player.id} value={player.id}>{player.team.shortName} · {player.displayName || `${player.firstName} ${player.lastName}`}</option>)}</select><button className="btn-primary w-full">Simulate voting burst</button></form></Tool>
    <Tool title="Undo latest simulation" description="Restore the automatic checkpoint created before the selected run."><form action="/api/admin/undo" method="post" className="space-y-3"><input type="hidden" name="action" value="simulation"/><select name="runId" className="w-full border border-line p-3"><option value="">Latest completed run</option>{runs.filter((run) => run.status === "COMPLETED").map((run) => <option key={run.id} value={run.id}>{run.kind} · {run.seed} · {run.createdAt.toLocaleString()}</option>)}</select><button className="btn border-red-600 bg-red-600 text-white w-full">Undo simulation</button></form></Tool>
  </div>}
  <section className="panel mt-6 overflow-x-auto"><div className="border-b border-line p-4"><h2 className="text-xl font-black uppercase">Recent simulation runs</h2></div><table className="w-full text-sm"><thead className="bg-ink text-left text-white"><tr><th className="p-3">Run</th><th className="p-3">Seed</th><th className="p-3">Status</th><th className="p-3">Created</th><th className="p-3">Error</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id} className="border-b border-line"><td className="p-3 font-bold">{run.kind}<div className="text-xs font-normal text-gray-500">{run.id}</div></td><td className="p-3 font-mono">{run.seed || "—"}</td><td className="p-3">{run.status}</td><td className="p-3">{run.createdAt.toLocaleString()}</td><td className="max-w-sm p-3 text-red-700">{run.error || "—"}</td></tr>)}</tbody></table></section></main>;
}
function Tool({ title, description, children }: { title: string; description: string; children: ReactNode }) { return <section className="panel p-5"><h2 className="text-xl font-black uppercase">{title}</h2><p className="mb-4 mt-1 text-sm text-gray-500">{description}</p>{children}</section>; }
function Seed() { return <label className="block"><span className="label">Simulation seed</span><input name="seed" defaultValue="20260729" className="mt-1 w-full border border-line p-3 font-mono"/></label>; }
function ScoreStyle() { return <select name="scoreStyle" className="w-full border border-line p-3"><option value="RANDOM">Random score</option><option value="DOMINANT">Dominant</option><option value="CLOSE">Close</option><option value="DEUCE">Deuce / extended</option></select>; }
function ScoreOptions() { return <div className="grid grid-cols-2 gap-3"><select name="matchupOutcome" className="border border-line p-3"><option value="RANDOM">Random outcomes</option><option value="HOME">Home-favored</option><option value="AWAY">Away-favored</option><option value="CLOSE_HOME">Close 4-3 home</option><option value="CLOSE_AWAY">Close 4-3 away</option></select><ScoreStyle/></div>; }
